# Generated by Django 3.2.9 on 2021-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(max_length=10)),
                ('batch', models.CharField(max_length=255)),
                ('sid', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
            ],
        ),
    ]
